[package]
name = "incremental_list"
version = "0.1.0"
authors = ["thundershield <schets@uw.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdrhistogram = "6.3.4"
rand = "0.7.0"
min-max-heap = "1.2.2"
